### ISSUE TITLE
Compiler source code

### ISSUE THREAD

**Issue by tihorygit** [davidberneda/Vidi#1]
Hi,
Vidi impressed me, kudos.
Can I check out the source? I'm eager to find out more about the internals.

**Comment by davidberneda** [comment]
Thanks a lot !
Sources will maybe be published once converted from Pascal to Vidi itself, right now they are quite messy, not ready yet. 
I'm just doing the minimum code to make it work and test, not very object-oriented. This will be done in a next phase.

**Comment by tihorygit** [comment]
I am even interested in checking how you made it with FPC. This is an interesting topic.

**Comment by davidberneda** [comment]
Sources are now available
